baseURL = "/blog"
languageCode = "en-us"
title = "blog."
theme = "anubis2"
disqusShortname = ""
publishDir = "public/blog"

[pagination]
pagerSize = 5

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params.author]
name = "gabrielzschmitz"
email  = "gabrielzschmitz@protonmail.com"
location = "Brasil"

[params]
description = "This is the gabrielzschmitz blog."
dateFormat = "2006-01-02"
paginationSinglePost = true

# icp = "京ICP备xxxxx号-1" # for China ICP license
# police = "京公网安备 12345678号" # for China police beian

colorTheme = "auto"
colorThemeSwitcher = true

readMore = false
readNextPosts = 2
copyCodeButton = true
rssAsSocialIcon = true
locale = "en-us"
math = false # true: enable mathjax globally (default is false)
toc = true

# Graphcomment support
graphcommentId = ""

social = [
    { id = "email", url = "mailto:gabrielzschmitz@protonmail.com" },
]

[[menu.main]]
identifier = "home"
name = "home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "tags"
name = "tags"
url = "/tags/"
weight = 3

[taxonomies]
category = "categories"
tag = "tags"
author = "authors"

[markup]
defaultMarkdownHandler = 'goldmark'

[markup.goldmark.renderer]
unsafe = true # Enable unsafe mode to have a better experience

[markup.highlight]
anchorLineNos      = false
codeFences         = true # tested with true and false. Both work.
noClasses          = true # If you run with markup.highlight.noClasses=false in your site configuration, you need a style sheet.
style              = 'catppuccin-frappe' # Find more style at here: https://swapoff.org/chroma/playground/
tabWidth           = 2
